### ISSUE TITLE
Variables are not highlighted within comments

### ISSUE THREAD

**Issue by tbhartman** [fadeevab/make.tmbundle#6]
Variables in `sh`-style comments should be highlighted accordingly.  Currently they are highlighted as part of the comment, but variables are substituted by `make` prior to the comment being formed.

Currently:
![image](https://user-images.githubusercontent.com/896331/63528926-d313a600-c4d1-11e9-80af-c9f750422a1c.png)

Should be:
![image](https://user-images.githubusercontent.com/896331/63528899-c55e2080-c4d1-11e9-95df-a6f482551937.png)

**Comment by fadeevab** [comment]
@tbhartman Thanks for the reported issue.

I think the simplest solution could be to highlight all variables in all comments, though Makefile doesn't care about its own comments, only about comments in recipes. Be careful with such approach, because there could be tricky things with a complex vars inside comments. Try ${shell echo "###" $(info babla)}.

**Comment by tbhartman** [comment]
@fadeevab seems to work with my PR:

![image](https://user-images.githubusercontent.com/896331/63530216-048d7100-c4d4-11e9-81ee-f51556290148.png)

**Comment by tbhartman** [comment]
@fadeevab Were you intending that the Makefile's own comments *not* have variables highlighted?  Might need to have better logic than #7:

![image](https://user-images.githubusercontent.com/896331/63530352-49b1a300-c4d4-11e9-8e7f-02a3a9e1a4cb.png)

**Comment by fadeevab** [comment]
@tbhartman Yeah, makefile doesn't care about vars in its own comments.
